require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3.0
  DisplayCopNames: true
  Exclude:
    - '**/config.ru'
    - '**/Rakefile'
    - 'bin/**/*'
    - 'tmp/**/*'
    - '*.gemspec'
    - '**/spec/spec_helper.rb'
    - '**/spec/support/inputs_outputs_pairs.rb'
    - '**/spec/app/**/*'
    - 'gemfiles/**/*'
    - 'vendor/**/*'
Documentation:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Max: 80
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
Metrics/AbcSize:
  Max: 23
Metrics/CyclomaticComplexity:
  Max: 7
Metrics/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*_spec.rb'
Metrics/MethodLength:
  Max: 25
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()
Style/RaiseArgs:
  EnforcedStyle: compact
Style/RegexpLiteral:
  StyleGuide: slashes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/StringLiterals:
  EnforcedStyle: single_quotes
