version: 2.0
defaults: &defaults
  working_directory: ~/repo
  steps:
    - run:
        name: Bundle
        command: bundle install
    - run:
        name: bin/ci
        command: bin/ci
jobs:
  ruby-240:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4.0
  ruby-250:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5.0
  ruby-260:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.6.0

workflows:
  version: 2

  commit:
    jobs:
      - ruby-240
      - ruby-250
      - ruby-260